export const GET_GAMES = 'GET_GAMES';
export const GET_TEAMINFO = 'GET_TEAMINFO';
export const SET_LOADING = 'SET_LOADING';
export const SET_OVERALLWINS = 'SET_OVERALLWINS';
export const SET_OVERALLLOSSES = 'SET_OVERALLLOSSES';
