export const GET_GAMES = 'GET_GAMES';
export const GET_TEAM_INFO = 'GET_TEAMINFO';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEASON_WINS = 'SET_SEASON_WINS';
export const SET_SEASON_LOSSES = 'SET_SEASON_LOSSES';
export const SET_HOME_WINS = 'SET_HOME_WINS';
export const SET_HOME_LOSSES = 'SET_HOME_LOSSES';
export const SET_AWAY_WINS = 'SET_AWAY_WINS';
export const SET_AWAY_LOSSES = 'SET_AWAY_LOSSES';
export const SET_CONFERENCE_WINS = 'SET_CONFERENCE_WINS';
export const SET_CONFERENCE_LOSSES = 'SET_CONFERENCE_LOSSES';
export const SET_YEAR = 'SET_YEAR';

export const GET_GAME_INFORMATION = 'GET_GAME_INFORMATION';
