export const GET_GAMES = 'GET_GAMES';
export const GET_TEAMINFO = 'GET_TEAMINFO';
export const SET_LOADING = 'SET_LOADING';
export const SET_SEASONWINS = 'SET_SEASONWINS';
export const SET_SEASONLOSSES = 'SET_SEASONLOSSES';
